name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate too Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install requirements
          pip install -r requirements.txt
          pip install "dvc[gs]"

          # Pull data & run-cache from S3 and reproduce pipeline
          dvc pull

          python probeai/train.py

          cat ./reports/classification_report.txt >> report.md
          echo "![](./reports/figures/confusion_matrix.png)" >> report.md
          cml comment create report.md
