name: model-training
on: [push]
jobs:
  run-prediction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          node-version: 16

    # - name: Authenticate to Google Drive
    #   uses: google-github-actions/auth@v1
    #   with:
    #     credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS2 }}

    - name: Set up CML
      uses: iterative/setup-cml@v1

    - name: Install DVC
      run: |
        pip install 'dvc[gdrive]'

    - uses: iterative/setup-dvc@v1
    - name: Get data
      run: dvc pull
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA2 }}

    - name: Run prediction model
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          # Install requirements
          pip install -r requirements.txt

          python probeai/train.py

          cat ./reports/classification_report.txt >> report.md
          echo "![](./reports/figures/confusion_matrix.png)" >> report.md
          cml comment create report.md
