name: model-training
on: [push]
jobs:
  run-prediction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS2 }}

    - name: Set up CML
      uses: iterative/setup-cml@v1

    - name: Install DVC
      run: |
        pip install 'dvc[gs]'

    - name: Pull data with DVC
      run: |
        dvc pull

    - name: Run prediction model
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          # Install requirements
          pip install -r requirements.txt

          python probeai/train.py

          cat ./reports/classification_report.txt >> report.md
          echo "![](./reports/figures/confusion_matrix.png)" >> report.md
          cml comment create report.md
